#!/usr/bin/env bash
BASE=frontend/src

# List all the files/folders you expect (relative to $BASE)
EXPECTED=(
  "App.css"
  "App.js"
  "App.js.bak"
  "App.test.js"
  "components/AboutSection/AboutSection.css"
  "components/AboutSection/AboutSection.jsx"
  "components/CheckoutForm/CheckoutForm.css"
  "components/CheckoutForm/CheckoutForm.jsx"
  "components/common/Button/Button.jsx"
  "components/common/Card/Card.jsx"
  "components/FAQSection/FAQSection.css"
  "components/FAQSection/FAQSection.jsx"
  "components/FeaturesSection/FeaturesSection.css"
  "components/FeaturesSection/FeaturesSection.jsx"
  "components/Footer/Footer.css"
  "components/Footer/Footer.jsx"
  "components/FounderModal/FounderModal.css"
  "components/FounderModal/FounderModal.jsx"
  "components/FounderOffer/FounderOffer.css"
  "components/FounderOffer/FounderOffer.jsx"
  "components/Header/Header.css"
  "components/Header/Header.jsx"
  "components/Hero/Hero.css"
  "components/Hero/Hero.jsx"
  "components/HomePage/HomePage.css"
  "components/HomePage/HomePage.jsx"
  "components/PricingSection/PricingSection.css"
  "components/PricingSection/PricingSection.jsx"
  "components/ProtectedRoute.jsx"
  "components/Spinner/Spinner.css"
  "components/Spinner/Spinner.jsx"

  "context/AuthContext.jsx"
  "context/ProjectContext.jsx"
  "context/WorkflowContext.jsx"
  "context/ThemeContext.jsx"
  "context/index.js"

  "hooks/useAuth.js"
  "hooks/useProject.js"
  "hooks/useWorkflow.js"
  "hooks/useAI.js"
  "hooks/useWebSocket.js"
  "hooks/useLocalStorage.js"
  "hooks/index.js"

  "pages/Account/Account.css"
  "pages/Account/Account.jsx"
  "pages/Blog/Blog.css"
  "pages/Blog/Blog.jsx"
  "pages/Dashboard/Dashboard.css"
  "pages/Dashboard/Dashboard.jsx"
  "pages/Enterprise/Enterprise.css"
  "pages/Enterprise/Enterprise.jsx"
  "pages/Login/Login.css"
  "pages/Login/Login.jsx"
  "pages/PaymentPage/PaymentPage.css"
  "pages/PaymentPage/PaymentPage.jsx"
  "pages/PricingResult/PricingResult.css"
  "pages/PricingResult/PricingResult.jsx"
  "pages/Sessions/Sessions.css"
  "pages/Sessions/Sessions.jsx"
  "pages/SignUp/SignUp.css"
  "pages/SignUp/SignUp.jsx"
  "pages/SmallBusiness/SmallBusiness.css"
  "pages/SmallBusiness/SmallBusiness.jsx"
  "pages/Solopreneurs/Solopreneurs.css"
  "pages/Solopreneurs/Solopreneurs.jsx"
  "pages/Wizard/Wizard.css"
  "pages/Wizard/Wizard.jsx"

  "pages/Ops/index.js"
  "pages/Ops/LSSDashboard.jsx"
  "pages/Ops/OpsDashboard.jsx"
  "pages/Ops/OpsDashboard.module.css"
  "pages/Ops/A3/A3.jsx"
  "pages/Ops/A3/A3.module.css"
  "pages/Ops/ANOVA/ANOVA.jsx"
  "pages/Ops/BoxPlot/BoxPlot.jsx"
  "pages/Ops/CapabilityAnalysis/CapabilityAnalysis.jsx"
  "pages/Ops/Checksheet/Checksheet.jsx"
  "pages/Ops/ControlChart/ControlChart.jsx"
  "pages/Ops/ControlPlan/ControlPlan.jsx"
  "pages/Ops/DataCollectionPlan/DataCollectionPlan.jsx"
  "pages/Ops/EffortImpactMatrix/EffortImpactMatrix.jsx"
  "pages/Ops/FMEA/FMEA.jsx"
  "pages/Ops/GapAnalysis/GapAnalysis.jsx"
  "pages/Ops/Histogram/Histogram.jsx"
  "pages/Ops/ImplementationPlan/ImplementationPlan.jsx"
  "pages/Ops/ProblemStatement/ProblemStatement.jsx"
  "pages/Ops/ProcessMap/ProcessMap.jsx"
  "pages/Ops/ProjectCharter/ProjectCharter.jsx"
  "pages/Ops/ProjectPlanning/ProjectPlanning.jsx"
  "pages/Ops/RootCauseAnalysis/RootCauseAnalysis.jsx"
  "pages/Ops/RunChart/RunChart.jsx"
  "pages/Ops/ScatterPlot/ScatterPlot.jsx"
  "pages/Ops/SIPOC/SIPOC.jsx"
  "pages/Ops/SolutionSelection/SolutionSelection.jsx"
  "pages/Ops/StakeholderAnalysis/StakeholderAnalysis.jsx"
  "pages/Ops/StandardWork/StandardWork.jsx"
  "pages/Ops/SustainmentPlan/SustainmentPlan.jsx"
  "pages/Ops/ValueStreamMap/ValueStreamMap.jsx"
  "pages/Ops/VoiceOfCustomer/VoiceOfCustomer.jsx"

  "reportWebVitals.js"
  "Routes.jsx"
  "services/api.js"
  "setupTests.js"
  "shared/auth/AuthContext.jsx"
  "shared/components/index.js"
  "shared/hooks/index.js"
  "shared/utils/index.js"
  "index.css"
  "index.js"
)

missing=()
for f in "${EXPECTED[@]}"; do
  if [ ! -e "$BASE/$f" ]; then
    missing+=("$f")
  fi
done

if [ ${#missing[@]} -eq 0 ]; then
  echo "✅ All expected files/folders are present under $BASE."
else
  echo "❌ Missing entries under $BASE:"
  printf '  - %s\n' "${missing[@]}"
fi
