"""Add subscription & credit fields

Revision ID: 290332f2a2b0
Revises: None
Create Date: 2025-07-06 13:12:25.241920

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '290332f2a2b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('subscription_plan', sa.String(length=50), nullable=False),
    sa.Column('seat_limit', sa.Integer(), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=True),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('unlimited_analysis', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=True),
    sa.Column('referral_code', sa.String(length=36), nullable=False),
    sa.Column('referrals_earned', sa.Integer(), nullable=False),
    sa.Column('feedback_earned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
